package Agricolas.vista;



import java.awt.Dimension;
import java.io.File;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;



/**
 *
 *
 */
public class MDIComercial extends javax.swing.JFrame {

    private Mantenimiento_Producto MantenimientoProducto;
    private Mantenimiento_Bodega Mantenimiento_Bodega;
    private Mantenimiento_Unidad MantenimientoUnidad;
    private Mantenimiento_Marca MantenimientoMarca;
    private Mantenimiento_Linea MantenimientoLinea;


   
    
    public static JLabel logo = new JLabel();

    public MDIComercial() throws UnknownHostException {
        initComponents();
        logo(0);


        String modulo_nombre = "Comercial";


    }

    public void logo(int activar) {
        Icon icon = new ImageIcon("C:src/main/java/Imagen/2.jpg");
        logo.setSize(300, 300);
        if (icon != null) {

            logo.setIcon(icon);
        } else {

        }
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = logo.getSize();
        logo.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        logo.setVisible(true);
        jdpescritorio.add(logo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpescritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        M_ccompras = new javax.swing.JMenu();
        M_inventario = new javax.swing.JMenu();
        Item_Mntbodega = new javax.swing.JCheckBoxMenuItem();
        Item_marca = new javax.swing.JCheckBoxMenuItem();
        Item_Linea = new javax.swing.JCheckBoxMenuItem();
        Item_Mntproducto = new javax.swing.JMenuItem();
        Item_Mntunidad = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        cerrar_sesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Hotelero");
        setResizable(false);

        jdpescritorio.setBackground(new java.awt.Color(204, 255, 204));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu1);

        M_ccompras.setText("Catalogos");
        M_ccompras.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        M_inventario.setText("Mantenimientos Inventarios");

        Item_Mntbodega.setSelected(true);
        Item_Mntbodega.setText("Mantenimiento Bodegas");
        Item_Mntbodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_MntbodegaActionPerformed(evt);
            }
        });
        M_inventario.add(Item_Mntbodega);

        Item_marca.setSelected(true);
        Item_marca.setText("Mantenimiento Marca");
        Item_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_marcaActionPerformed(evt);
            }
        });
        M_inventario.add(Item_marca);

        Item_Linea.setSelected(true);
        Item_Linea.setText("Mantenimiento Linea");
        Item_Linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_LineaActionPerformed(evt);
            }
        });
        M_inventario.add(Item_Linea);

        Item_Mntproducto.setText("Mantenimiento Producto");
        Item_Mntproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_MntproductoActionPerformed(evt);
            }
        });
        M_inventario.add(Item_Mntproducto);

        Item_Mntunidad.setSelected(true);
        Item_Mntunidad.setText("Mantenimiento Unidad");
        Item_Mntunidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_MntunidadActionPerformed(evt);
            }
        });
        M_inventario.add(Item_Mntunidad);

        M_ccompras.add(M_inventario);

        jMenuBar1.add(M_ccompras);

        jMenu4.setText("Procesos");
        jMenu4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu12.setText("Informes");
        jMenu12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu12);

        jMenu6.setText("Herramientas");
        jMenu6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu6);

        cerrar_sesion.setText("Cerrar Sesión");
        cerrar_sesion.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cerrar_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrar_sesionMouseClicked(evt);
            }
        });
        jMenuBar1.add(cerrar_sesion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpescritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 1229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpescritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void cerrar_sesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrar_sesionMouseClicked
        int respuesta_cs = JOptionPane.showConfirmDialog(this, "¿Desea Cerrar Sesión?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION);
        if (respuesta_cs == 0) {
            this.dispose();
        }

    }//GEN-LAST:event_cerrar_sesionMouseClicked

    private void Item_MntproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_MntproductoActionPerformed
        MantenimientoProducto = new Mantenimiento_Producto();
        jdpescritorio.add(MantenimientoProducto);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = MantenimientoProducto.getSize();
        MantenimientoProducto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        MantenimientoProducto.show();
        logo.setVisible(true);
        MantenimientoProducto.setVisible(true);

    }//GEN-LAST:event_Item_MntproductoActionPerformed

    private void Item_MntbodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_MntbodegaActionPerformed
        Mantenimiento_Bodega = new Mantenimiento_Bodega();
        jdpescritorio.add(Mantenimiento_Bodega);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = Mantenimiento_Bodega.getSize();
        Mantenimiento_Bodega.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Mantenimiento_Bodega.show();
        logo.setVisible(true);
        Mantenimiento_Bodega.setVisible(true);


    }//GEN-LAST:event_Item_MntbodegaActionPerformed

    private void Item_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_marcaActionPerformed
        // TODO add your handling code here:
        MantenimientoMarca = new Mantenimiento_Marca();
        jdpescritorio.add(MantenimientoMarca);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = MantenimientoMarca.getSize();
        MantenimientoMarca.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        MantenimientoMarca.show();
        logo.setVisible(true);
        MantenimientoMarca.setVisible(true);
    }//GEN-LAST:event_Item_marcaActionPerformed

    private void Item_LineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_LineaActionPerformed
        // TODO add your handling code here:
        MantenimientoLinea = new Mantenimiento_Linea();
        jdpescritorio.add(MantenimientoLinea);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = MantenimientoLinea.getSize();
        MantenimientoLinea.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        MantenimientoLinea.show();
        logo.setVisible(true);
        MantenimientoLinea.setVisible(true);

    }//GEN-LAST:event_Item_LineaActionPerformed

    private void Item_MntunidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_MntunidadActionPerformed
        // TODO add your handling code here:
        MantenimientoUnidad = new Mantenimiento_Unidad();
        jdpescritorio.add(MantenimientoUnidad);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = MantenimientoUnidad.getSize();
        MantenimientoUnidad.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        MantenimientoUnidad.show();
        logo.setVisible(true);
        MantenimientoUnidad.setVisible(true);
    }//GEN-LAST:event_Item_MntunidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
//            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            System.out.println(ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MDIComercial().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(MDIComercial.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem Item_Linea;
    private javax.swing.JCheckBoxMenuItem Item_Mntbodega;
    public static javax.swing.JMenuItem Item_Mntproducto;
    private javax.swing.JCheckBoxMenuItem Item_Mntunidad;
    private javax.swing.JCheckBoxMenuItem Item_marca;
    public static javax.swing.JMenu M_ccompras;
    public static javax.swing.JMenu M_inventario;
    public static javax.swing.JMenu cerrar_sesion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    public static javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JDesktopPane jdpescritorio;
    // End of variables declaration//GEN-END:variables
}
